# Generated by Django 4.1.1 on 2023-02-02 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='monthly_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
