# Generated by Django 4.1.1 on 2023-02-02 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_monthlytransaction_delete_budget'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyTransaction',
        ),
    ]
