# Generated by Django 4.1.1 on 2023-02-20 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_delete_monthlytransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
