# Generated by Django 4.1.1 on 2023-03-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0011_remove_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
