# Generated by Django 4.1.1 on 2023-03-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0012_alter_transaction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='goal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
