# Generated by Django 4.2.3 on 2025-04-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0013_account_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('chequing', 'Chequing'), ('savings', 'Savings'), ('credit', 'Credit Card'), ('investment', 'Investment'), ('crypto', 'Crypto')], default='chequing', max_length=20),
        ),
    ]
