# Generated by Django 4.2.3 on 2025-04-10 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0014_account_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='type',
            new_name='account_type',
        ),
    ]
