# Generated by Django 4.2.3 on 2025-04-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0015_rename_type_account_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='manual_balance',
            field=models.BooleanField(default=True),
        ),
    ]
