# Generated by Django 4.2.3 on 2025-04-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0016_account_manual_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='manual_balance',
        ),
        migrations.AddField(
            model_name='account',
            name='starting_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
