# Generated by Django 4.2.3 on 2025-04-11 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0017_remove_account_manual_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transfer_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='to_account', to='budget.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_account', to='budget.account'),
        ),
    ]
