# Generated by Django 4.2.3 on 2025-04-11 02:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0018_transaction_transfer_to_alter_transaction_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='crypto_amount',
            field=models.DecimalField(blank=True, decimal_places=8, default=Decimal('0.0'), max_digits=20, null=True),
        ),
    ]
