# Generated by Django 4.2.3 on 2025-04-11 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0019_account_crypto_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='crypto_amount',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=18, null=True),
        ),
    ]
