# Generated by Django 4.2.3 on 2024-10-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_featured_image_alter_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='original_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
