# Generated by Django 4.2.3 on 2024-11-01 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0007_recipebook_grocerylist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipebook',
            name='is_recipe_book',
        ),
        migrations.AlterField(
            model_name='recipebook',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
