# Generated by Django 4.2.3 on 2026-01-03 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0008_remove_recipebook_is_recipe_book_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookbookUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='cookbook_uploads/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cookbook_uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_guess', models.CharField(blank=True, max_length=500)),
                ('raw_text', models.TextField()),
                ('parsed_title', models.CharField(blank=True, max_length=500)),
                ('parsed_ingredients', models.JSONField(blank=True, default=list)),
                ('parsed_steps', models.JSONField(blank=True, default=list)),
                ('confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imported', models.BooleanField(default=False)),
                ('imported_recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_draft', to='recipes.recipe')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='recipes.cookbookupload')),
            ],
        ),
    ]
